export const CARD_SELECTED = 'CARD_SELECTED';
export const GAME_RESTART = 'GAME_RESTART';
export const FOUND_GROUP = 'FOUND_GROUP';
export const CHANGE_QUALITIES = 'CHANGE_QUALITIES';
export const CHANGE_SUBTYPES = 'CHANGE_SUBTYPES';
